from __future__ import annotations

from django.urls import URLPattern, path

from . import views

app_name = "rpg"
urlpatterns: list[URLPattern] = [
    path(
        "quests/<int:quest_id>/complete/",
        views.complete_quest_api,
        name="quest_complete",
    ),
    path(
        "quests/<int:quest_id>/progress/",
        views.update_quest_progress_api,
        name="quest_progress",
    ),
    path(
        "habits/<int:habit_id>/toggle/",
        views.toggle_habit_api,
        name="habit_toggle",
    ),
    path("campaigns/", views.campaigns_api, name="campaigns"),
    path(
        "campaigns/ai-drafts/",
        views.campaign_ai_drafts_api,
        name="campaign_ai_drafts",
    ),
    path(
        "campaigns/<int:campaign_id>/",
        views.campaign_detail_api,
        name="campaign_detail",
    ),
    path(
        "campaigns/<int:campaign_id>/activate/",
        views.campaign_activate_api,
        name="campaign_activate",
    ),
    path(
        "campaigns/<int:campaign_id>/publish/",
        views.campaign_publish_api,
        name="campaign_publish",
    ),
    path(
        "campaigns/<int:campaign_id>/studio/",
        views.campaign_studio_api,
        name="campaign_studio",
    ),
    path(
        "campaigns/<int:campaign_id>/validate/",
        views.campaign_validate_api,
        name="campaign_validate",
    ),
    path(
        "campaigns/<int:campaign_id>/archive/",
        views.campaign_archive_api,
        name="campaign_archive",
    ),
    path(
        "campaigns/<int:campaign_id>/nodes/",
        views.campaign_nodes_api,
        name="campaign_nodes",
    ),
    path(
        "campaigns/<int:campaign_id>/nodes/positions/",
        views.campaign_node_positions_api,
        name="campaign_node_positions",
    ),
    path(
        "campaigns/<int:campaign_id>/nodes/<int:node_id>/",
        views.campaign_node_detail_api,
        name="campaign_node_detail",
    ),
    path(
        "campaigns/<int:campaign_id>/edges/",
        views.campaign_edges_api,
        name="campaign_edges",
    ),
    path(
        "campaigns/<int:campaign_id>/edges/<int:edge_id>/",
        views.campaign_edge_detail_api,
        name="campaign_edge_detail",
    ),
    path(
        "campaigns/<int:campaign_id>/quests/",
        views.campaign_add_quest_api,
        name="campaign_add_quest",
    ),
    path(
        "campaigns/<int:campaign_id>/dependencies/",
        views.campaign_dependencies_api,
        name="campaign_dependencies",
    ),
    path("goals/", views.goals_api, name="goals"),
    path("goals/<int:goal_id>/", views.goal_detail_api, name="goal_detail"),
    path(
        "goals/<int:goal_id>/progress/",
        views.goal_progress_api,
        name="goal_progress",
    ),
    path(
        "goals/<int:goal_id>/complete/",
        views.goal_complete_api,
        name="goal_complete",
    ),
    path(
        "goals/<int:goal_id>/archive/",
        views.goal_archive_api,
        name="goal_archive",
    ),
    path("challenges/", views.challenges_api, name="challenges"),
    path(
        "challenges/<int:challenge_id>/",
        views.challenge_detail_api,
        name="challenge_detail",
    ),
    path(
        "challenges/<int:challenge_id>/toggle/",
        views.challenge_toggle_api,
        name="challenge_toggle",
    ),
    path(
        "challenges/<int:challenge_id>/complete/",
        views.challenge_complete_api,
        name="challenge_complete",
    ),
    path(
        "challenges/<int:challenge_id>/fail/",
        views.challenge_fail_api,
        name="challenge_fail",
    ),
    path("achievements/", views.achievements_api, name="achievements"),
    path(
        "achievements/<int:achievement_id>/unlock/",
        views.achievement_unlock_api,
        name="achievement_unlock",
    ),
    path(
        "achievements/evaluate/",
        views.achievement_evaluate_api,
        name="achievement_evaluate",
    ),
    path(
        "journal/",
        views.journal_entries_api,
        name="journal_create",
    ),
    path(
        "journal/<int:entry_id>/",
        views.journal_entry_detail_api,
        name="journal_entry_detail",
    ),
]
