# Generated by Django 6.0.6 on 2026-06-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydefinition',
            name='life_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_definitions', to='skills.lifearea'),
        ),
        migrations.AddField(
            model_name='activityentry',
            name='activity_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='activities.activitydefinition'),
        ),
        migrations.AddField(
            model_name='activityreward',
            name='activity_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='activities.activitydefinition'),
        ),
        migrations.AddField(
            model_name='activityreward',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_rewards', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='activityrule',
            name='activity_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='activities.activitydefinition'),
        ),
        migrations.AddConstraint(
            model_name='activityentry',
            constraint=models.CheckConstraint(condition=models.Q(('minutes__gt', 0)), name='activities_entry_minutes_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='activityreward',
            constraint=models.UniqueConstraint(fields=('activity_definition', 'skill'), name='activities_reward_unique_activity_skill'),
        ),
        migrations.AddConstraint(
            model_name='activityreward',
            constraint=models.CheckConstraint(condition=models.Q(('xp_per_minute__gt', 0)), name='activities_reward_xp_per_minute_gt_0'),
        ),
    ]
