# Generated by Django 6.0.6 on 2026-06-09 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='statuses.statusdefinition')),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 100)), name='statuses_entry_value_0_100')],
            },
        ),
    ]
