# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LlmProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("chatgpt", "ChatGPT"),
                            ("claude", "Claude"),
                            ("gemini", "Gemini"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("api_key", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider"],
            },
        ),
    ]
