# Generated by Django 6.0.6 on 2026-06-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("one_time", "One time"),
                            ("ai_generated", "AI generated"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("normal", "Normal"),
                            ("hard", "Hard"),
                            ("epic", "Epic"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("target_value", models.PositiveIntegerField(default=1)),
                (
                    "target_unit",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("minutes", "Minutes"),
                            ("steps", "Steps"),
                            ("pages", "Pages"),
                            ("check", "Check"),
                        ],
                        default="count",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("system", "System"),
                            ("ai", "AI"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                ("available_until", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("target_value__gt", 0)),
                        name="rpg_quest_target_value_gt_0",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_on", models.DateField()),
                ("progress_value", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("xp_awarded_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="rpg.quest",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_on", "quest__sort_order", "quest__title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("quest", "completed_on"),
                        name="rpg_quest_completion_unique_quest_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("progress_value__gte", 0)),
                        name="rpg_quest_completion_progress_gte_0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp_amount", models.PositiveIntegerField()),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="rpg.quest",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_rewards",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["quest__title", "skill__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("quest", "skill"),
                        name="rpg_quest_reward_unique_quest_skill",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("xp_amount__gt", 0)),
                        name="rpg_quest_reward_xp_gt_0",
                    ),
                ],
            },
        ),
    ]
