# Generated by Django 6.0.6 on 2026-06-10 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("target_value", models.PositiveIntegerField(default=1)),
                (
                    "target_unit",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("minutes", "Minutes"),
                            ("steps", "Steps"),
                            ("pages", "Pages"),
                            ("check", "Check"),
                        ],
                        default="check",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="rpg_habit_unique_name"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("target_value__gt", 0)),
                        name="rpg_habit_target_value_gt_0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HabitMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("streak_days", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="rpg.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["streak_days", "title"],
            },
        ),
        migrations.CreateModel(
            name="HabitMilestoneReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp_amount", models.PositiveIntegerField()),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="rpg.habitmilestone",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_milestone_rewards",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["milestone__streak_days", "skill__name"],
            },
        ),
        migrations.CreateModel(
            name="HabitMilestoneUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("xp_awarded_at", models.DateTimeField(blank=True, null=True)),
                ("streak_days", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_unlocks",
                        to="rpg.habit",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="rpg.habitmilestone",
                    ),
                ),
            ],
            options={
                "ordering": ["-unlocked_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_on", models.DateField()),
                ("value", models.PositiveIntegerField(default=1)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="rpg.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_on", "habit__sort_order", "habit__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("habit", "checked_on"),
                        name="rpg_habit_checkin_unique_habit_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value__gte", 0)),
                        name="rpg_habit_checkin_value_gte_0",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="habitmilestone",
            constraint=models.UniqueConstraint(
                fields=("habit", "streak_days"),
                name="rpg_habit_milestone_unique_habit_days",
            ),
        ),
        migrations.AddConstraint(
            model_name="habitmilestone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("habit__isnull", True)),
                fields=("streak_days",),
                name="rpg_habit_milestone_unique_global_days",
            ),
        ),
        migrations.AddConstraint(
            model_name="habitmilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(("streak_days__gt", 0)),
                name="rpg_habit_milestone_streak_days_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="habitmilestonereward",
            constraint=models.UniqueConstraint(
                fields=("milestone", "skill"),
                name="rpg_habit_milestone_reward_unique_milestone_skill",
            ),
        ),
        migrations.AddConstraint(
            model_name="habitmilestonereward",
            constraint=models.CheckConstraint(
                condition=models.Q(("xp_amount__gt", 0)),
                name="rpg_habit_milestone_reward_xp_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="habitmilestoneunlock",
            constraint=models.UniqueConstraint(
                fields=("milestone", "habit"),
                name="rpg_habit_milestone_unlock_unique_milestone_habit",
            ),
        ),
        migrations.AddConstraint(
            model_name="habitmilestoneunlock",
            constraint=models.CheckConstraint(
                condition=models.Q(("streak_days__gt", 0)),
                name="rpg_habit_milestone_unlock_streak_days_gt_0",
            ),
        ),
    ]
