# Generated by Django 6.0.6 on 2026-06-10 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0002_habit_habitmilestone_habitmilestonereward_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("content", models.TextField(blank=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("quest", "Quest"),
                            ("habit", "Habit"),
                            ("habit_milestone", "Habit milestone"),
                            ("challenge", "Challenge"),
                            ("achievement", "Achievement"),
                            ("system", "System"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("mood", models.CharField(blank=True, max_length=40)),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "entry_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-entry_date", "-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="rpg_journal_entry_title_not_empty",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            models.Q(("source_type", ""), _negated=True),
                            ("source_id__isnull", False),
                        ),
                        fields=("source_type", "source_id"),
                        name="rpg_journal_entry_unique_source",
                    ),
                ],
            },
        ),
    ]
