# Generated by Django 6.0.6 on 2026-06-10 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0003_journalentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="reflection_challenge",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reflection_goal_action",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reflection_improve",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reflection_learned",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reflection_proud",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ready_for_battle", "Ready for Battle"),
                    ("focused", "Focused"),
                    ("balanced", "Balanced"),
                    ("tired", "Tired"),
                    ("exhausted", "Exhausted"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="CharacterIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "started_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("ended_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active", "-started_on", "-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="rpg_character_identity_title_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_on__isnull", True),
                            ("ended_on__gte", models.F("started_on")),
                            _connector="OR",
                        ),
                        name="rpg_character_identity_end_gte_start",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="rpg_character_identity_single_active",
                    ),
                ],
            },
        ),
    ]
