# Generated by Django 6.0.6 on 2026-06-10 17:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0004_journalentry_reflection_challenge_and_more"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("quest", "Quest"),
                    ("habit", "Habit"),
                    ("habit_milestone", "Habit milestone"),
                    ("goal", "Goal"),
                    ("challenge", "Challenge"),
                    ("achievement", "Achievement"),
                    ("system", "System"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("total_xp", "Total XP"),
                            ("skill_level", "Skill level"),
                            ("quest_count", "Quest count"),
                            ("habit_streak", "Habit streak"),
                            ("challenge_completed", "Challenge completed"),
                            ("goal_completed", "Goal completed"),
                            ("journal_streak", "Journal streak"),
                        ],
                        default="manual",
                        max_length=40,
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                ("icon", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code", ""), _negated=True),
                        name="rpg_achievement_code_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="rpg_achievement_title_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("legendary", "Legendary"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("target_value", models.PositiveIntegerField(default=1)),
                ("progress_value", models.PositiveIntegerField(default=0)),
                (
                    "target_unit",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("minutes", "Minutes"),
                            ("steps", "Steps"),
                            ("pages", "Pages"),
                            ("check", "Check"),
                        ],
                        default="count",
                        max_length=20,
                    ),
                ),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("due_on", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("system", "System"),
                            ("ai", "AI"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "life_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="skills.lifearea",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "due_on", "title"],
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("target_value", models.PositiveIntegerField(default=30)),
                (
                    "target_unit",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("minutes", "Minutes"),
                            ("steps", "Steps"),
                            ("pages", "Pages"),
                            ("check", "Check"),
                        ],
                        default="check",
                        max_length=20,
                    ),
                ),
                ("current_value", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("xp_awarded_at", models.DateTimeField(blank=True, null=True)),
                ("reward_title", models.CharField(blank=True, max_length=180)),
                (
                    "created_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("system", "System"),
                            ("ai", "AI"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="rpg.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "end_date", "-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="GoalProgressEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_value", models.PositiveIntegerField()),
                ("new_value", models.PositiveIntegerField()),
                ("delta", models.IntegerField()),
                ("note", models.TextField(blank=True)),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="rpg.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_skills",
                        to="rpg.goal",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["goal__sort_order", "skill__name"],
            },
        ),
        migrations.CreateModel(
            name="AchievementUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="rpg.achievement",
                    ),
                ),
            ],
            options={
                "ordering": ["-unlocked_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("achievement",),
                        name="rpg_achievement_unlock_unique_achievement",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChallengeCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_on", models.DateField()),
                ("value", models.PositiveIntegerField(default=1)),
                ("successful", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="rpg.challenge",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-checked_on",
                    "challenge__sort_order",
                    "challenge__title",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("challenge", "checked_on"),
                        name="rpg_challenge_checkin_unique_challenge_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value__gte", 0)),
                        name="rpg_challenge_checkin_value_gte_0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChallengeReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp_amount", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="rpg.challenge",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_rewards",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["challenge__title", "skill__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("challenge", "skill"),
                        name="rpg_challenge_reward_unique_challenge_skill",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("xp_amount__gt", 0)),
                        name="rpg_challenge_reward_xp_gt_0",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="rpg_goal_title_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_value__gt", 0)),
                name="rpg_goal_target_value_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("progress_value__gte", 0)),
                name="rpg_goal_progress_value_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("progress_value__lte", models.F("target_value"))),
                name="rpg_goal_progress_lte_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_on__isnull", True),
                    ("starts_on__isnull", True),
                    ("due_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="rpg_goal_due_on_gte_starts_on",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="rpg_challenge_title_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_value__gt", 0)),
                name="rpg_challenge_target_value_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_value__gte", 0)),
                name="rpg_challenge_current_value_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_value__lte", models.F("target_value"))),
                name="rpg_challenge_current_lte_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="rpg_challenge_end_gte_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("failed_at__isnull", True),
                    _connector="OR",
                ),
                name="rpg_challenge_not_completed_and_failed",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalprogressentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("previous_value__gte", 0)),
                name="rpg_goal_progress_previous_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalprogressentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_value__gte", 0)),
                name="rpg_goal_progress_new_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalprogressentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("source_type", ""), _negated=True),
                    ("source_id__isnull", False),
                ),
                fields=("goal", "source_type", "source_id"),
                name="rpg_goal_progress_unique_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalskill",
            constraint=models.UniqueConstraint(
                fields=("goal", "skill"), name="rpg_goal_skill_unique_goal_skill"
            ),
        ),
        migrations.AddConstraint(
            model_name="goalskill",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gt", 0)), name="rpg_goal_skill_weight_gt_0"
            ),
        ),
    ]
