# Generated by Django 6.0.6 on 2026-06-10 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0005_alter_journalentry_entry_type_achievement_goal_and_more"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("total_xp", "Total XP"),
                    ("skill_level", "Skill level"),
                    ("quest_count", "Quest count"),
                    ("habit_streak", "Habit streak"),
                    ("challenge_completed", "Challenge completed"),
                    ("goal_completed", "Goal completed"),
                    ("campaign_completed", "Campaign completed"),
                    ("journal_streak", "Journal streak"),
                ],
                default="manual",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("quest", "Quest"),
                    ("habit", "Habit"),
                    ("habit_milestone", "Habit milestone"),
                    ("goal", "Goal"),
                    ("challenge", "Challenge"),
                    ("campaign", "Campaign"),
                    ("achievement", "Achievement"),
                    ("system", "System"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI"), ("system", "System")],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("normal", "Normal"),
                            ("hard", "Hard"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("due_on", models.DateField(blank=True, null=True)),
                ("reward_xp", models.PositiveIntegerField(default=0)),
                ("reward_title", models.CharField(blank=True, max_length=180)),
                ("ai_prompt", models.TextField(blank=True)),
                ("ai_provider", models.CharField(blank=True, max_length=40)),
                ("ai_model", models.CharField(blank=True, max_length=120)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("xp_awarded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "life_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="skills.lifearea",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_rewards",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_on", "title"],
            },
        ),
        migrations.CreateModel(
            name="CampaignQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(blank=True, max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "unlock_mode",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("after_dependencies", "After dependencies"),
                            ("manual", "Manual"),
                        ],
                        default="after_dependencies",
                        max_length=30,
                    ),
                ),
                ("map_x", models.PositiveIntegerField(default=0)),
                ("map_y", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_quests",
                        to="rpg.campaign",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_links",
                        to="rpg.quest",
                    ),
                ),
            ],
            options={
                "ordering": ["campaign", "stage", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignQuestDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign_quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="rpg.campaignquest",
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="rpg.campaignquest",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "campaign_quest__campaign",
                    "campaign_quest__order",
                    "depends_on__order",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="rpg_campaign_title_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("reward_xp__gte", 0)),
                name="rpg_campaign_reward_xp_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_on__isnull", True),
                    ("starts_on__isnull", True),
                    ("due_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="rpg_campaign_due_on_gte_starts_on",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignquest",
            constraint=models.UniqueConstraint(
                fields=("campaign", "quest"),
                name="rpg_campaign_quest_unique_campaign_quest",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignquest",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 0)),
                name="rpg_campaign_quest_order_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignquest",
            constraint=models.CheckConstraint(
                condition=models.Q(("map_x__gte", 0)),
                name="rpg_campaign_quest_map_x_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignquest",
            constraint=models.CheckConstraint(
                condition=models.Q(("map_y__gte", 0)),
                name="rpg_campaign_quest_map_y_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignquestdependency",
            constraint=models.UniqueConstraint(
                fields=("campaign_quest", "depends_on"),
                name="rpg_campaign_dependency_unique_edge",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignquestdependency",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("campaign_quest", models.F("depends_on")), _negated=True
                ),
                name="rpg_campaign_dependency_not_self",
            ),
        ),
    ]
