# Generated by Django 6.0.6 on 2026-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=180)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("work", "Work"),
                            ("rpg", "RPG"),
                            ("health", "Health"),
                            ("finance", "Finance"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_at", "end_at", "title"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="planner_calendar_event_title_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gte", models.F("start_at"))),
                        name="planner_calendar_event_end_gte_start",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            models.Q(("source_type", ""), _negated=True),
                            ("source_id__isnull", False),
                        ),
                        fields=("source_type", "source_id"),
                        name="planner_calendar_event_unique_source",
                    ),
                ],
            },
        ),
    ]
