# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_frequency",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_group",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
